### PR TITLE
Fixed a missing `}` in `getInteger()` due to merge-up conflict resolution

### PR DESCRIPTION
**Pull request by japaveh**
|    Q          |   A
|-------------- | ------
| Documentation |no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
There was a missing } in getInteger() and this Pull Request fixes this issue

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems only in 3.4.0 branch, apply to 3.4.0 milestone.

**Review by samsonasik — APPROVED** [review]

**Comment by Ocramius** [comment]
O_O looks like a merge conflict issue? Incredible this made it through, and really shows that we need to get off travis-ci ASAP

**Comment by samsonasik** [comment]
Yes, it seems

**Comment by Ocramius** [comment]
Thanks @japaveh!

**Pull request merged**
