### PR TITLE
Drop support php 7, add php 8.2 support

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
@Ocramius : i don't know why the tests `testUnsupportedPlatform` is not working anymore and i don't know whats it is supposed to do....

**Comment by Ocramius** [comment]
I think we'd need @ezimuel's input here.

**Comment by ezimuel** [comment]
@Ocramius, @fezfez You can remove the `RandTest::testUnsupportedPlatform()`. This test was related with https://github.com/zendframework/zend-math/pull/36 that is no more relevant with PHP 8.

**Comment by fezfez** [comment]
@ezimuel thanks for info, it's done

**Review by Ocramius — APPROVED** [review]
Excellent, thanks @fezfez and @ezimuel!

**Pull request merged**
