### PR TITLE
Add caution admonition to README maintenance note

### PR DESCRIPTION
**Pull request by froschdesign**
Inserted a caution admonition to clarify the package's maintenance status. This change aims to ensure that users pay close attention to its security-only maintenance mode while providing appropriate context and links for further information.

### CODE REVIEW

**Review by gsteel — APPROVED** [review]
I think the vote to abandon this lib passed though

**Comment by gsteel** [comment]
https://laminas.slack.com/archives/G4QT8RUE9/p1733082375598689

**Comment by froschdesign** [comment]
Now I have found it too! Unfortunately, nobody has adapted the custom properties.

**Comment by froschdesign** [comment]
> Unfortunately, nobody has adapted the custom properties.

Done!

**Comment by gsteel** [comment]
I haven't actioned the archive process for all the votes from Monday yet - they are all still to do… We can abandon and release 8.4 support here at the same time and test the docs layout 👍

**Pull request closed without merging**
